In [1]:
import numpy as np

## 배열의 index 접근

In [33]:
# 1차원 배열
arr = np.arange(10)
print(arr)
print(arr[3])
print(arr[1])
print(arr[-1])
print(arr[-3])
print(arr[-10])

[0 1 2 3 4 5 6 7 8 9]
3
1
9
7
0


In [34]:
# 2차원 배열
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr, arr.shape, "\n", arr.ndim)
print(arr[0][3])
print(arr[0,3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4) 
 2
4
4


In [35]:
arr = np.arange(10)
print(arr[3:8])
print(arr[3:])
print(arr[:6])
print(arr[:-1])

[3 4 5 6 7]
[3 4 5 6 7 8 9]
[0 1 2 3 4 5]
[0 1 2 3 4 5 6 7 8]


In [36]:
# 2차원 배열
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr[0,:])
print(arr[:,1])
print(arr[:3, :])
print(arr[:2, 2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 2 3 4]
[ 2  6 10]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[3 4]
 [7 8]]


## Fancy indexing

In [44]:
# 1차원 배열
arr = np.arange(0, 31, 5)
print(arr)
print(arr[[0,2,4]])

[ 0  5 10 15 20 25 30]
[ 0 10 20]


In [45]:
# 2차원 배열
arr = np.array([[5,10,15,20],
               [25,30,35,40],
               [45,50,55,60]])
print(arr)
print(arr[[0,2], 2:])
print(arr[1:, [2, 3]])

[[ 5 10 15 20]
 [25 30 35 40]
 [45 50 55 60]]
[[15 20]
 [55 60]]
[[35 40]
 [55 60]]
